version = 5.3.1
archive_dir = /etc/letsencrypt/archive/chat.pavloman.ru
cert = /etc/letsencrypt/live/chat.pavloman.ru/cert.pem
privkey = /etc/letsencrypt/live/chat.pavloman.ru/privkey.pem
chain = /etc/letsencrypt/live/chat.pavloman.ru/chain.pem
fullchain = /etc/letsencrypt/live/chat.pavloman.ru/fullchain.pem
[renewalparams]
account = 9eccd5f5df80f5bc08c019669fe8946a
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
chat.pavloman.ru = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-03-01T03:40:39
